Repository yunionio/jsonutils, pull requests merged in 2019-06, with the labels that each got.

#9 fix: jsonutils ignore nil pointers
  querystring.go
  utils.go
Labels: approved, lgtm, size/S

#10 fix: add GetAnyString2 to return key of string
  utils.go
Labels: lgtm, size/S

#11 use github.com/ghodss/yaml as yaml utils
  .gitignore
  OWNERS
  go.mod
  go.sum
  jsonutils.go
  yamlutils.go
  yamlutils_test.go
Labels: approved, lgtm, size/L
