Repository yunionio/jsonutils, pull requests merged in 2019-12, with the labels that each got.

#13 JSONInt结构体增加Float()float64函数
  access.go
Labels: approved, lgtm, size/XS

#14 fix: querystring format jsonarray
  access.go
  errors.go
  jsonutils.go
  querystring.go
  querystring_test.go
  reflect.go
  stringsegment.go
  stringsegment_test.go
  unmarshal.go
  utils.go
Labels: approved, lgtm, size/L

#16 feature: allow unmarshal json string into []string
  unmarshal.go
  unmarshal_test.go
Labels: approved, lgtm, size/S

#15 unmarshal: fix error reporting
  unmarshal.go
Labels: approved, lgtm, size/S

#19 fix endless loop on get array at jsondict with jsondict
  access.go
Labels: approved, lgtm, size/XS

#17 feature: Faster Marshall and UnMarshall
  access.go
  marshal.go
Labels: size/XS
