Repository yunionio/jsonutils, pull requests merged in 2020-11, with the labels that each got.

#43 fix: fail to encode/decode strings ignore special chars
  access_test.go
  jsonutils.go
Labels: size/M

#44 fix: encode specials chars as byte in json string
  access_test.go
  jsonutils.go
Labels: size/L

#45 marshal: return null for nil ptr (inc. interface with type)
  .circleci/config.yml
  marshal.go
  marshal_test.go
Labels: size/S
