Repository yunionio/jsonutils, pull requests merged in 2020-08, with the labels that each got.

#37 update json float string output format
  string.go
Labels: approved, lgtm, size/XS

#36 BUG: fix new time string with utc time zone
  utils.go
  utils_test.go
Labels: approved, lgtm, size/S

#38 Feature/yousong i18n
  .gitignore
  errors.go
  go.mod
  go.sum
  locales/doc.go
  locales/locales.go
  locales/zh-CN/messages.gotext.json
  utils.go
Labels: approved, lgtm, size/L

#39 fix: TAG_PREFIX invalid syntax
  go.mod
  go.sum
  marshal_test.go
  unmarshal_test.go
Labels: approved, lgtm, size/S
